# Generated by Django 4.1.13 on 2024-06-21 14:00

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                        verbose_name="Source Currency",
                    ),
                ),
                (
                    "target_currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("JPY", "Japanese Yen"),
                        ],
                        max_length=3,
                        verbose_name="Target Currency",
                    ),
                ),
                (
                    "source_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Source Amount"
                    ),
                ),
                (
                    "converted_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Converted Amount"
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The User which is associated to this transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transactions",
                "ordering": ["-created"],
            },
        ),
    ]
