# Generated by Django 4.1.10 on 2023-08-15 13:07

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import authentication.utils.secrets


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfAgreement",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "terms_of_agreement",
                    models.TextField(verbose_name="Terms of Agreement"),
                ),
            ],
            options={
                "verbose_name": "Terms of Agreement",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="UserTermsOfAgreement",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "terms_of_agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="who_accepted_terms_of_agreement",
                        to="authentication.termsofagreement",
                        verbose_name="Terms of Agreement ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms_of_agreement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who accepted the term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Who Accepted Terms of Agreement",
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=authentication.utils.secrets.generate_code,
                        max_length=6,
                        verbose_name="Code",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESET_PASSWORD_REQUEST", "RESET_PASSWORD_REQUEST"),
                            ("USER_CONFIRMATION", "USER_CONFIRMATION"),
                        ],
                        max_length=25,
                        verbose_name="Type",
                    ),
                ),
                (
                    "was_used",
                    models.BooleanField(default=False, verbose_name="Was already used?"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The User which is associated to this",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code",
                "ordering": ("-created",),
            },
        ),
    ]
